[workspace]

# members = ["crates/stringmetrics", "crates/stringmetrics_py"]
# members = ["crates/stringmetrics", "crates/stringmetrics_py"]
members = ["crates/stringmetrics", "crates/stringmetrics_py"]
