[package]
name = "stringmetrics"
version = "1.0.2"
edition = "2021"
description = "Rust library for approximate string matching"
license-file = "LICENSE"
repository = "https://github.com/pluots/stringmetrics-rust"
# This won't auto link for some reason, no harm in having it manual
documentation = "https://docs.rs/stringmetrics"


[dependencies]
# itertools = "0.10.3"
# isolang = "2.1.0"
regex = "1"
lazy_static = "1.4"
unicode-segmentation = "1.9.0"
stringmetrics-derive = { path = "stringmetrics-derive" }
strum_macros = "0.24"
strum = { version = "0.24", features = ["derive"] }
# enum-map = "2"


[dev-dependencies]
# more-asserts = "0.2.2"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]
