[package]
name = "stringmetrics_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = {version = "1.0.98", features = ["extra-traits", "derive", "parsing"] }
quote = "1.0.19"
proc-macro2 = "1.0.39"

[lib]
proc-macro = true

[package.metadata.release]
shared-version = true
