[package]
name = "stringmetrics-derive"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/pluots/stringmetrics-rust"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
