on: [pull_request]

name: Cargo build check

jobs:
  build_and_test:
    name: "Build and test: cargo-build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
