name: "Python wheels: build test"

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  linux_wheels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: messense/maturin-action@v1
      with:
        manylinux: auto
        command: build
        args: --release -o dist --manifest-path crates/stringmetrics_py/Cargo.toml
    - uses: messense/maturin-action@v1
      with:
        maturin-version: "0.13"
        target: x86_64-unknown-linux-musl
        manylinux: musllinux_1_1
        command: build
        args: --release -o dist --find-interpreter --manifest-path crates/stringmetrics_py/Cargo.toml
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist
